roles:
  - src: geerlingguy.docker
    version: "7.4.7"
  - src: gantsign.golang
    version: "3.5.0"
  - src: geerlingguy.apache
    version: "4.0.0"
  - src: stephdewit.nvm
    version: "v3.4.5"

collections:
  - name: ansible.posix
    version: "2.1.0"
  - name: community.general
    version: "11.2.0"
  - name: community.postgresql
    version: "4.1.0"
