- name: Copy files to snippets
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/lib/vz/snippets/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - users.yml
    - vendor.yml

- name: Ensure packages are installed
  ansible.builtin.package:
    name:
      - debian-archive-keyring
      - proxmox-archive-keyring

- name: Remove /etc/apt/sources.list if it exists
  ansible.builtin.file:
    path: /etc/apt/sources.list
    state: absent

- name: Configure Ceph Repository
  ansible.builtin.deb822_repository:
    name: ceph
    types: deb
    uris: http://download.proxmox.com/debian/ceph-squid
    suites: "{{ ansible_distribution_release }}"
    components: no-subscription
    signed_by: /usr/share/keyrings/proxmox-archive-keyring.gpg

- name: Configure Debian Repository
  ansible.builtin.deb822_repository:
    name: debian
    types: deb
    uris: http://deb.debian.org/debian/
    suites: "{{ ansible_distribution_release }}"
    components: main contrib non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

- name: Configure Debian Updates Repository
  ansible.builtin.deb822_repository:
    name: debian-updates
    types: deb
    uris: http://deb.debian.org/debian/
    suites: "{{ ansible_distribution_release }}-updates"
    components: main contrib non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

- name: Configure Debian Security Repository
  ansible.builtin.deb822_repository:
    name: debian-security
    types: deb
    uris: http://security.debian.org/debian-security/
    suites: "{{ ansible_distribution_release }}-security"
    components: main contrib non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

- name: Enable Proxmox Non-Subscription Repository
  ansible.builtin.deb822_repository:
    name: proxmox
    types: deb
    uris: http://download.proxmox.com/debian/pve
    suites: "{{ ansible_distribution_release }}"
    components: pve-no-subscription
    signed_by: /usr/share/keyrings/proxmox-archive-keyring.gpg

- name: Disable Proxmox Enterprise Repository
  ansible.builtin.deb822_repository:
    name: pve-enterprise
    types: deb
    uris: http://enterprise.proxmox.com/debian/pve
    suites: "{{ ansible_distribution_release }}"
    components: pve-enterprise
    signed_by: /usr/share/keyrings/proxmox-archive-keyring.gpg
    state: absent

- name: Ensure Non-Free-Firmware doesn't present a warning
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/no-bookworm-firmware.conf
    line: 'APT::Get::Update::SourceListWarnings::NonFreeFirmware "false";'

- name: Remove Subscription Nag
  ansible.builtin.copy:
    src: no-nag-script
    dest: /etc/apt/apt.conf.d/no-nag-script
    owner: root
    group: root
    mode: '0644'

- name: Install intel-microcode Package
  ansible.builtin.apt:
    name: intel-microcode
    autoclean: true
    autoremove: true
    update_cache: true

- name: Remove systemd-boot
  ansible.builtin.apt:
    name: intel-microcode
    state: absent

- name: Configure Network Interfaces
  ansible.builtin.template:
    backup: true
    dest: /etc/network/interfaces
    src: interfaces.j2
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload network interfaces
