- name: Install ISC Repository
  ansible.builtin.include_role:
    name: isc_repo

- name: Install Kea
  ansible.builtin.apt:
    name: isc-kea
    state: present
    update_cache: true

- name: Install Stork Agent
  ansible.builtin.include_role:
    name: stork_agent
  tags: stork_agent
