#cloud-config
users:
  - default
  - name: ansible
    gecos: Ansible User
    groups: users,admin,wheel
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPi5VSGIo5q8/5ZwEXr2Qw+Sy1i6SPw24GPFKUSqeaHP'