- name: Copy tanium-client-bundle.zip
  ansible.builtin.copy:
    src: tanium-client-bundle.zip
    dest: /tmp/tanium-client-bundle.zip
    mode: '0644'
  tags: tanium

- name: Ensure Unzip
  ansible.builtin.package:
    name: unzip
    state: present
  tags: tanium

- name: Create target directory
  ansible.builtin.file:
    path: /tmp/tanium-client-bundle
    state: directory
    mode: '0755'
  tags: tanium

- name: Unzip Tanium Client
  ansible.builtin.unarchive:
    src: /tmp/tanium-client-bundle.zip
    dest: /tmp/tanium-client-bundle
    remote_src: true
    mode: '0755'
  tags: tanium
